_wdt:
    resource: "@WebProfilerBundle/Resources/config/routing/wdt.xml"
    prefix:   /_wdt

_profiler:
    resource: "@WebProfilerBundle/Resources/config/routing/profiler.xml"
    prefix:   /_profiler

_configurator:
    resource: "@SensioDistributionBundle/Resources/config/routing/webconfigurator.xml"
    prefix:   /_configurator

_main:
    resource: routing.yml

# AcmeDemoBundle routes (to be removed)
#_acme_demo:
#    resource: "@AcmeDemoBundle/Resources/config/routing.yml"

_welcome:
    pattern:  /
    defaults: { _controller: AcmeDemoBundle:Github:index }

_login_page:
    path: /github/login
    defaults:  { _controller: AcmeDemoBundle:Github:login }

_browser_page:
    path: /github/browser
    defaults:  { _controller: AcmeDemoBundle:Github:browser }

_github_secured:
    resource: "@AcmeDemoBundle/Controller/SecuredController.php"
    type:     annotation

_github:
     resource: "@AcmeDemoBundle/Controller/GithubController.php"
     type:     annotation
     prefix:   /github